[general]
import = [
  "~/Development/NullVoxPopuli/dotfiles/home/.config/alacritty/themes/horizon-dark.toml"
]


[font]
size = 14

[font.normal]
family = "NotoSansM Nerd Font Mono"
# family = "AnonymicePro Nerd Font Mono"
# family = "0xProto Nerd Font Mono"
# family = "CodeNewRoman Nerd Font Mono"
# family = "DejaVuSansMono Nerd Font Mono"


[mouse]
hide_when_typing = false

[terminal.shell]
args = ["--login"]
program = "/opt/homebrew/bin/bash"

[window]
option_as_alt = "OnlyLeft"
decorations = "None"

# https://github.com/alacritty/alacritty/issues/5246#issuecomment-1878166299
[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[keyboard]
bindings = [
  # Should be macOS default
  { key = "F11", action = "ToggleSimpleFullscreen" },

  # With same directory
  { mods= "Control|Shift", key = "n", action = "CreateNewWindow" },

  # Muscle memory from elsewhere
  # control+d for now, don't know how to make alt-f4 work
  # { mods = "Alt", key = "F4", chars = "^D" },
  { mods = "Control|Shift", key = "C", action = "Copy" },
  { mods = "Control|Shift", key = "V", action = "Paste" },

  # Allow certain characters to pass through to underlying TUIs
  { mods = "Control", key = "Slash", chars = "\u001F" },

  # These are nice
  { mods="Option", key="c", action = "ScrollHalfPageUp" },
  { mods="Option", key="t", action = "ScrollHalfPageDown" }
]
