[font.normal]
family = "CodeNewRoman Nerd Font Mono"

[general]
import = [
  "~/.config/alacritty/themes/horizon-dark.toml"
]

[window]
decorations = "None"

# https://github.com/alacritty/alacritty/issues/5246#issuecomment-1878166299
[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

